apiVersion: bprocessorld.openshift.io/v1
kind: BprocessorldConfig
metadata:
  labels:
    app: processor
  name: processor
  namespace: calculator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: processor:latest
  runPolicy: Serial
  source:
    contextDir: microservices/calculator/processor
    git:
      ref: master
      uri: https://github.com/abalasu1/IBM-Private-Cloud.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./Dockerfile
    type: Source
