apiVersion: v1
kind: Service
metadata:
  labels:
    app: processor
  name: processor
  namespace: calculator
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: processor
  type: NodePort
