apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: quoteapi
  name: quoteapi
  namespace: quotemachine
spec:
  lookupPolicy:
    local: true
status:
  dockerImageRepository: <CONTAINER>
  tags:
  - items:
    tag: latest
