apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: httpbin-deployable
  annotations:
    app.ibm.com/is-local-deployable: "false"
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: httpbin
      namespace: httpbin
    spec:
      selector:
        matchLabels:
          app: httpbin
      replicas: 1
      template:
        metadata:
          labels:
            app: httpbin
        spec:
          containers:
          - image: docker.io/citizenstig/httpbin
            imagePullPolicy: IfNotPresent
            name: httpbin
            ports:
            - containerPort: 8000
  placement:
    clusters:
    - name: local-cluster
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: httpbin-svc-deployable
  annotations:
    app.ibm.com/is-local-deployable: "false"
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: httpbin
      namespace: httpbin
      annotations:
        mcm.ibm.com/service-discovery: "{}"
    spec:
      type: NodePort
      selector:
        app: httpbin
      ports:
      - name: http
        port: 8000
  placement:
    clusters:
    - name: local-cluster
