apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: multiservicesapp
  namespace: multiservicesapp
  labels:
    app: multiservicesapp
spec:
  selector:
    matchLabels:
      app: multiservicesapp
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
    
