apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: multiservicesapp
  namespace: multiservicesapp
  labels:
    app: multiservicesapp
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      region: EU
  resourceHint:
    type: cpu
