apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: compositeop-mirror
  namespace: <PROJECT>
spec:
  hosts:
    - compositeop
  http:
  - route:
    - destination:
        host: compositeop
        subset: v1
      weight: 100
    mirror:
      host: compositeop
      subset: v2