apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: processor
  namespace: <PROJECT>
spec:
  host: processor
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      app: processor
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: timeout
  namespace: <PROJECT>
spec:
  hosts:
  - processor
  http:
  - route:
    - destination:
        host: processor
        subset: v1        
    timeout: 10s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fixeddelay
  namespace: <PROJECT>  
spec:
  hosts:
  - compositeop
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 30s
    route:
    - destination:
        host: compositeop
        subset: v1