apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: subtract
  name: subtract
  namespace: calculator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: subtract:latest
  runPolicy: Serial
  source:
    contextDir: microservices/calculator/subtract
    git:
      ref: master
      uri: https://github.com/abalasu1/IBM-Private-Cloud.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
