apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: compositeop-ts2
  namespace: <PROJECT>
spec:
  hosts:
  - compositeop
  http:
  - match:
    - uri:
        prefix: "/compositeop"  
    route:
    - destination:
        host: compositeop
        subset: v1
      weight: 10
    - destination:
        host: compositeop
        subset: v2
      weight: 10
    - destination:
        host: compositeop
        subset: v3
      weight: 80