apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: compositeop
  name: compositeop
  namespace: calculator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: compositeop:latest
  runPolicy: Serial
  source:
    contextDir: microservices/calculator/compositeop
    git:
      ref: master
      uri: https://github.com/abalasu1/IBM-Private-Cloud.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./Dockerfile
    type: Source
