apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: add
  name: add
  namespace: calculator
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/calculator/add
  tags:
  - items:
    tag: latest
