apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: denybasicophandler
  namespace: calculator-mesh
spec:
  compiledAdapter: denier
  params:
    status:
      code: 7
      message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: denybasicoprequest
  namespace: calculator-mesh  
spec:
  compiledTemplate: checknothing
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denybasicop
  namespace: calculator-mesh  
spec:
  match: destination.labels["app"] == "add"
  actions:
  - handler: denybasicophandler
    instances: [ denybasicoprequest ]