apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: divide
  name: divide
  namespace: <PROJECT>
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: <CONTAINER>
  tags:
  - items:
    tag: latest
