apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: divide
  name: divide
  namespace: calculator
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/calculator/divide
  tags:
  - items:
    tag: latest
