apiVersion: v1
kind: Service
metadata:
  name: compositeop
  namespace: <PROJECT>
  labels:
    app: compositeop
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: compositeop
