apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multiply
  namespace: <PROJECT>
  labels:
    app: multiply
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: multiply
    spec:
      containers:
      - name: multiply
        image: <CONTAINER>
