apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: simpleapp
  namespace: simpleapp
  labels:
    app: simpleapp
spec:
  selector:
    matchLabels:
      app: simpleapp
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
    
