apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: simpleapp
  namespace: simpleapp
  labels:
    app: simpleapp
spec:
  type: contains
  source:
    kind: Application
    name: simpleapp
  destination:
    kind: Deployable
    name: simpleapp
