apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: simpleapp
  namespace: simpleapp
  labels:
    app: simpleapp
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://github.com/abalasu1/IBM-Cloud-Private/raw/master/Mcm/charts/simpleapp.tgz
      namespace: simpleapp
