apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: simpleapp
  namespace: simpleapp
  labels:
    app: simpleapp
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      region: EU
  resourceHint:
    type: cpu
